/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BrandDesc: typeof import('./src/components/brand/BrandDesc.vue')['default']
    ClassifyLeft: typeof import('./src/components/classify/ClassifyLeft.vue')['default']
    ClassifyRight: typeof import('./src/components/classify/ClassifyRight.vue')['default']
    DemoView: typeof import('./src/components/demo/DemoView.vue')['default']
    FreshGood: typeof import('./src/components/home/homeFloorItem/FreshGood.vue')['default']
    HomeBrand: typeof import('./src/components/home/homeFloorItem/HomeBrand.vue')['default']
    HomeFloor: typeof import('./src/components/home/homeFloor/HomeFloor.vue')['default']
    HomeNav: typeof import('./src/components/home/homeNav/HomeNav.vue')['default']
    HomePopular: typeof import('./src/components/home/homeFloorItem/HomePopular.vue')['default']
    LightningDeals: typeof import('./src/components/home/homeFloorItem/LightningDeals.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperView: typeof import('./src/components/swiper/SwiperView.vue')['default']
    TabbarView: typeof import('./src/components/tabbar/TabbarView.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
