/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClassifyLeft: typeof import('./src/components/classify/ClassifyLeft.vue')['default']
    ClassifyRight: typeof import('./src/components/classify/ClassifyRight.vue')['default']
    DemoView: typeof import('./src/components/demo/DemoView.vue')['default']
    FreshGood: typeof import('./src/components/home/homeFloorItem/FreshGood.vue')['default']
    HomeBrand: typeof import('./src/components/home/homeFloorItem/HomeBrand.vue')['default']
    HomeFloor: typeof import('./src/components/home/homeFloor/HomeFloor.vue')['default']
    HomeNav: typeof import('./src/components/home/homeNav/HomeNav.vue')['default']
    HomePopular: typeof import('./src/components/home/homeFloorItem/HomePopular.vue')['default']
    LightningDeals: typeof import('./src/components/home/homeFloorItem/LightningDeals.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperView: typeof import('./src/components/swiper/SwiperView.vue')['default']
    TabbarView: typeof import('./src/components/tabbar/TabbarView.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanCell: typeof import('vant/es')['Cell']
    VanIcon: typeof import('vant/es')['Icon']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
